### ISSUE TITLE
Bleak Async call failing ... no attribute 

### ISSUE THREAD

**Issue by KarlBrennan** [ttu/ruuvitag-sensor#204]
Running on Windows 10 19042.2251
Python 3.11.1
Fresh build with only Ruuvitag_sensor 2.0.0 and Bleak 0.19.5 installed
I can see sensors using direct Bleak code namely
     devices = await BleakScanner.discover() 

Raw code is a copy of the example of the Bleak code provided in GitHub ... no modifications made (copied below)
--------------------------------------------------------------------
import asyncio
import os
os.environ['RUUVI_BLE_ADAPTER'] = 'bleak'

from ruuvitag_sensor.ruuvi import RuuviTagSensor
import ruuvitag_sensor.log

ruuvitag_sensor.log.enable_console()

async def main():
    async for data in RuuviTagSensor.get_data_async():
        print(data)

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())

------------------------------------------------------------------------------------------
Error details are as follows:
 
  Message=type object 'RuuviTagSensor' has no attribute 'get_data_async'
  Source=C:\Users\xxx\Development\Python\Bleak_Examples\Bleak_Example2.py
  StackTrace:
  File "C:\Users\xxx\Development\Python\Bleak_Examples\Bleak_Example2.py", line 11, in main (Current frame)
    async for data in RuuviTagSensor.get_data_async():
  File "C:\Users\xxx\Development\Python\Bleak_Examples\Bleak_Example2.py", line 15, in <module>
    asyncio.get_event_loop().run_until_complete(main())

**Comment by ttu** [comment]
Hi! Thanks for the issue.

Unfortunately, this functionality is not yet released in pip. 
https://github.com/ttu/ruuvitag-sensor/blob/master/CHANGELOG.md#unreleased

Was trying to get the last async features completed before releasing a new version, but as an afterthought, should have just released what I have already earlier. If you want to start using this functionality, you can install the development version from GitHub.

```sh
$ python -m pip install git+https://github.com/ttu/ruuvitag-sensor
```
